# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fkmdWPuAmpMbayDqaR6CDBJ0H_zMhTFl

EXP 1
**bold text**
"""

import numpy as np
import random

# ─────────────────────────────────────────
# 1. GRID-WORLD ENVIRONMENT
# ─────────────────────────────────────────

# Grid layout (4x4):
#  S  .  .  .
#  .  X  .  X
#  .  .  .  X
#  X  .  .  G
#
#  S = Start (0,0), G = Goal (3,3), X = Hole (penalty)

GRID_SIZE   = 4
START_STATE = (1, 0)
GOAL_STATE  = (3, 0)
HOLES       = {(1, 1), (1, 3), (2, 3)}  # instant penalty cells

# Actions: 0=Up, 1=Down, 2=Left, 3=Right
ACTIONS      = [0, 1, 2, 3]
ACTION_NAMES = ["Up", "Down", "Left", "Right"]

def step(state, action):
    """Take an action in the environment, return (next_state, reward, done)."""
    r, c = state

    if   action == 0: r -= 1   # Up
    elif action == 1: r += 1   # Down
    elif action == 2: c -= 1   # Left
    elif action == 3: c += 1   # Right

    # Clamp within grid boundaries
    r = max(0, min(GRID_SIZE - 1, r))
    c = max(0, min(GRID_SIZE - 1, c))

    next_state = (r, c)

    # Assign reward
    if next_state == GOAL_STATE:
        return next_state, +10, True   # Reached goal
    elif next_state in HOLES:
        return next_state, -5,  True   # Fell in hole
    else:
        return next_state, -1,  False  # Normal step penalty


# ─────────────────────────────────────────
# 2. Q-LEARNING ALGORITHM
# ─────────────────────────────────────────

# Hyperparameters
EPISODES    = 500      # Total training episodes
ALPHA       = 0.1      # Learning rate
GAMMA       = 0.9      # Discount factor
EPSILON     = 1.0      # Initial exploration rate
EPSILON_MIN = 0.01     # Minimum exploration rate
EPSILON_DECAY = 0.99   # Decay per episode

# Initialize Q-table with zeros: shape = (rows, cols, num_actions)
Q = np.zeros((GRID_SIZE, GRID_SIZE, len(ACTIONS)))

rewards_per_episode = []

for episode in range(EPISODES):
    state   = START_STATE
    total_reward = 0

    for _ in range(100):  # Max 100 steps per episode
        r, c = state

        # ── ε-greedy action selection ──
        if random.uniform(0, 1) < EPSILON:
            action = random.choice(ACTIONS)           # Explore
        else:
            action = np.argmax(Q[r, c])               # Exploit

        # ── Take action ──
        next_state, reward, done = step(state, action)
        nr, nc = next_state

        # ── Q-value update (Bellman equation) ──
        old_value  = Q[r, c, action]
        future_max = np.max(Q[nr, nc])
        Q[r, c, action] = old_value + ALPHA * (reward + GAMMA * future_max - old_value)

        state        = next_state
        total_reward += reward

        if done:
            break

    # Decay epsilon after each episode
    EPSILON = max(EPSILON_MIN, EPSILON * EPSILON_DECAY)
    rewards_per_episode.append(total_reward)


# ─────────────────────────────────────────
# 3. RESULTS
# ─────────────────────────────────────────

print("=" * 40)
print("   Q-LEARNING TRAINING COMPLETE")
print("=" * 40)

# Average reward over last 100 episodes
avg = np.mean(rewards_per_episode[-100:])
print(f"\nAvg reward (last 100 episodes): {avg:.2f}")

# ── Learned policy ──
print("\nLearned Policy (Best Action per Cell):")
print("  " + "  ".join([f" {c}" for c in range(GRID_SIZE)]))
for r in range(GRID_SIZE):
    row = ""
    for c in range(GRID_SIZE):
        if (r, c) == GOAL_STATE:
            symbol = " G"
        elif (r, c) in HOLES:
            symbol = " X"
        else:
            best = np.argmax(Q[r, c])
            arrows = ["↑", "↓", "←", "→"]
            symbol = f" {arrows[best]}"
        row += symbol + " "
    print(f"{r} {row}")

# ── Test: run one greedy episode ──
print("\n--- Test Run (Greedy Policy) ---")
state = START_STATE
path  = [state]
for _ in range(20):
    r, c   = state
    action = np.argmax(Q[r, c])
    state, reward, done = step(state, action)
    path.append(state)
    if done:
        break

print("Path taken:", " → ".join(str(s) for s in path))
if path[-1] == GOAL_STATE:
    print("✅ Agent reached the GOAL!")
else:
    print("❌ Agent did not reach the goal.")



"""EXP 2 **bold text**"""

import numpy as np
import matplotlib.pyplot as plt

# ─────────────────────────────────────────
# SETUP — User Input
# ─────────────────────────────────────────

NUM_ARMS  = int(input("Number of arms: "))
NUM_STEPS = int(input("Number of steps: "))

TRUE_PROBS = []
for i in range(NUM_ARMS):
    p = float(input(f"  True reward probability for Arm {i+1}: "))
    TRUE_PROBS.append(p)

EPSILON     = float(input("Epsilon (e.g. 0.1): "))
TEMPERATURE = float(input("Softmax Temperature (e.g. 0.5): "))

# ─────────────────────────────────────────
# HELPER — Pull an arm
# ─────────────────────────────────────────

def pull(arm):
    return 1 if np.random.random() < TRUE_PROBS[arm] else 0

# ─────────────────────────────────────────
# STRATEGY 1 — Epsilon-Greedy
# ─────────────────────────────────────────

counts = np.zeros(NUM_ARMS)
values = np.zeros(NUM_ARMS)
eg_rewards = []

for t in range(NUM_STEPS):
    arm = np.random.randint(NUM_ARMS) if np.random.random() < EPSILON else np.argmax(values)
    r = pull(arm)
    counts[arm] += 1
    values[arm] += (r - values[arm]) / counts[arm]
    eg_rewards.append(r)

# ─────────────────────────────────────────
# STRATEGY 2 — UCB
# ─────────────────────────────────────────

counts = np.zeros(NUM_ARMS)
values = np.zeros(NUM_ARMS)
ucb_rewards = []

for t in range(1, NUM_STEPS + 1):
    arm = t - 1 if t <= NUM_ARMS else np.argmax(values + np.sqrt(2 * np.log(t) / (counts + 1e-9)))
    r = pull(arm)
    counts[arm] += 1
    values[arm] += (r - values[arm]) / counts[arm]
    ucb_rewards.append(r)

# ─────────────────────────────────────────
# STRATEGY 3 — Softmax
# ─────────────────────────────────────────

counts = np.zeros(NUM_ARMS)
values = np.zeros(NUM_ARMS)
sm_rewards = []

for t in range(NUM_STEPS):
    exp_v = np.exp(values / TEMPERATURE)
    probs = exp_v / np.sum(exp_v)
    arm = np.random.choice(NUM_ARMS, p=probs)
    r = pull(arm)
    counts[arm] += 1
    values[arm] += (r - values[arm]) / counts[arm]
    sm_rewards.append(r)

# ─────────────────────────────────────────
# RESULTS
# ─────────────────────────────────────────

print(f"\nBest Arm: Arm {np.argmax(TRUE_PROBS)+1} (prob={max(TRUE_PROBS):.2f})")
print(f"e-Greedy  --> Avg Reward: {np.mean(eg_rewards):.3f}")
print(f"UCB       --> Avg Reward: {np.mean(ucb_rewards):.3f}")
print(f"Softmax   --> Avg Reward: {np.mean(sm_rewards):.3f}")

# ─────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────

steps = np.arange(1, NUM_STEPS + 1)

plt.plot(steps, np.cumsum(eg_rewards)  / steps, label=f"e-Greedy (e={EPSILON})")
plt.plot(steps, np.cumsum(ucb_rewards) / steps, label="UCB")
plt.plot(steps, np.cumsum(sm_rewards)  / steps, label=f"Softmax (T={TEMPERATURE})")
plt.axhline(max(TRUE_PROBS), linestyle="--", color="red", label="Best Arm Prob")
plt.title("Multi-Armed Bandit - Average Reward over Time")
plt.xlabel("Steps")
plt.ylabel("Avg Reward")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("bandit_comparison.png", dpi=150)
plt.show()
print("Plot saved as bandit_comparison.png")

"""EXP **3**"""

import numpy as np

# ─────────────────────────────────────────
# SETUP
# ─────────────────────────────────────────

def ask(prompt, default):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else str(default)

def get_pos(prompt, default, rows, cols):
    while True:
        raw = ask(prompt, default)
        try:
            r, c = map(int, raw.split())
            if 0 <= r < rows and 0 <= c < cols:
                return (r, c)
            print(f"  ✗ Must be within (0-{rows-1}, 0-{cols-1})")
        except:
            print("  ✗ Enter row and col e.g. 0 0")

print("=" * 50)
print("  DRONE DELIVERY MDP")
print("  (Press Enter to use defaults)")
print("=" * 50)

ROWS        = int(ask("\nGrid rows",    4))
COLS        = int(ask("Grid cols",     4))
MAX_BATTERY = int(ask("Max battery",  10))
GAMMA       = float(ask("Gamma",     0.9))
P_INTENDED  = float(ask("Prob intended move succeeds", 0.7))

print()
START    = get_pos("Start position",           "0 0",                 ROWS, COLS)
DELIVERY = get_pos("Delivery (goal) position", f"{ROWS-1} {COLS-1}", ROWS, COLS)

num_chargers = int(ask("Number of charging stations", 2))
CHARGERS = set()
charger_defaults = ["0 3", "2 1"]
for i in range(num_chargers):
    CHARGERS.add(get_pos(f"  Charger {i+1}", charger_defaults[i] if i < 2 else "0 0", ROWS, COLS))

num_obstacles = int(ask("Number of obstacles", 2))
OBSTACLES = set()
obs_defaults = ["1 2", "2 3"]
for i in range(num_obstacles):
    OBSTACLES.add(get_pos(f"  Obstacle {i+1}", obs_defaults[i] if i < 2 else "1 1", ROWS, COLS))

# ─────────────────────────────────────────
# MDP
# ─────────────────────────────────────────

MOVES        = [(-1,0),(1,0),(0,-1),(0,1)]
ACTION_NAMES = ["Up","Down","Left","Right"]
NUM_ACTIONS  = 4
THETA        = 1e-6

def is_valid(r, c):
    return 0 <= r < ROWS and 0 <= c < COLS and (r, c) not in OBSTACLES

def get_transitions(r, c, a):
    """Returns list of (nr, nc, prob) — probabilistic wind drift."""
    sideways = [MOVES[i] for i in range(NUM_ACTIONS) if i != a]
    p_side   = (1 - P_INTENDED) / len(sideways)

    raw = [(MOVES[a], P_INTENDED)] + [(s, p_side) for s in sideways]

    merged = {}
    for move, prob in raw:
        nr = r + move[0]
        nc = c + move[1]
        if not is_valid(nr, nc):
            nr, nc = r, c    # bounce back
        key = (nr, nc)
        merged[key] = merged.get(key, 0) + prob

    # Return as (nr, nc, prob)
    return [(nr, nc, prob) for (nr, nc), prob in merged.items()]

def get_reward(nr, nc, new_bat):
    if (nr, nc) == DELIVERY: return +20
    if new_bat == 0:          return -10
    if (nr, nc) in CHARGERS:  return  +2
    return -1

def is_terminal(r, c, bat):
    return (r, c) == DELIVERY or bat == 0

def next_battery(nr, nc, bat):
    if (nr, nc) in CHARGERS:
        return min(bat + 3, MAX_BATTERY)
    return max(bat - 1, 0)

# ─────────────────────────────────────────
# VALUE ITERATION
# ─────────────────────────────────────────

print("\nRunning Value Iteration...")
V = np.zeros((ROWS, COLS, MAX_BATTERY + 1))

vi_iter = 0
while True:
    delta = 0
    for r in range(ROWS):
        for c in range(COLS):
            if (r, c) in OBSTACLES:
                continue
            for bat in range(MAX_BATTERY + 1):
                if is_terminal(r, c, bat):
                    V[r, c, bat] = get_reward(r, c, bat)
                    continue
                best = -np.inf
                for a in range(NUM_ACTIONS):
                    val = 0
                    for nr, nc, prob in get_transitions(r, c, a):
                        nb  = next_battery(nr, nc, bat)
                        val += prob * (get_reward(nr, nc, nb) + GAMMA * V[nr, nc, nb])
                    best = max(best, val)
                delta        = max(delta, abs(best - V[r, c, bat]))
                V[r, c, bat] = best
    vi_iter += 1
    if delta < THETA:
        break

print(f"  Converged in {vi_iter} iterations.")

# Extract VI policy at full battery
vi_policy = np.zeros((ROWS, COLS), dtype=int)
for r in range(ROWS):
    for c in range(COLS):
        if (r, c) in OBSTACLES or is_terminal(r, c, MAX_BATTERY):
            continue
        best_a, best_v = 0, -np.inf
        for a in range(NUM_ACTIONS):
            val = 0
            for nr, nc, prob in get_transitions(r, c, a):
                nb  = next_battery(nr, nc, MAX_BATTERY)
                val += prob * (get_reward(nr, nc, nb) + GAMMA * V[nr, nc, nb])
            if val > best_v:
                best_v, best_a = val, a
        vi_policy[r, c] = best_a

# ─────────────────────────────────────────
# POLICY ITERATION
# ─────────────────────────────────────────

print("Running Policy Iteration...")
policy = np.zeros((ROWS, COLS, MAX_BATTERY + 1), dtype=int)
V2     = np.zeros((ROWS, COLS, MAX_BATTERY + 1))

pi_iter = 0
while True:
    # Policy Evaluation
    while True:
        delta = 0
        for r in range(ROWS):
            for c in range(COLS):
                if (r, c) in OBSTACLES:
                    continue
                for bat in range(MAX_BATTERY + 1):
                    if is_terminal(r, c, bat):
                        V2[r, c, bat] = get_reward(r, c, bat)
                        continue
                    val = 0
                    for nr, nc, prob in get_transitions(r, c, policy[r, c, bat]):
                        nb  = next_battery(nr, nc, bat)
                        val += prob * (get_reward(nr, nc, nb) + GAMMA * V2[nr, nc, nb])
                    delta        = max(delta, abs(val - V2[r, c, bat]))
                    V2[r, c, bat] = val
        if delta < THETA:
            break

    # Policy Improvement
    stable = True
    for r in range(ROWS):
        for c in range(COLS):
            if (r, c) in OBSTACLES:
                continue
            for bat in range(MAX_BATTERY + 1):
                if is_terminal(r, c, bat):
                    continue
                old_a = policy[r, c, bat]
                best_a, best_v = 0, -np.inf
                for a in range(NUM_ACTIONS):
                    val = 0
                    for nr, nc, prob in get_transitions(r, c, a):
                        nb  = next_battery(nr, nc, bat)
                        val += prob * (get_reward(nr, nc, nb) + GAMMA * V2[nr, nc, nb])
                    if val > best_v:
                        best_v, best_a = val, a
                policy[r, c, bat] = best_a
                if old_a != best_a:
                    stable = False
    pi_iter += 1
    if stable:
        break

print(f"  Converged in {pi_iter} iterations.")

# ─────────────────────────────────────────
# RESULTS
# ─────────────────────────────────────────

arrows = ["↑","↓","←","→"]

def print_grid(label, pol_2d, V_grid):
    print(f"\n{label}")
    print("    " + "  ".join(f" C{c}" for c in range(COLS)))
    for r in range(ROWS):
        row = f"R{r} "
        for c in range(COLS):
            if   (r,c) in OBSTACLES:   row += "  X  "
            elif (r,c) == DELIVERY:    row += "  G  "
            elif (r,c) in CHARGERS:    row += f" {arrows[pol_2d[r,c]]}⚡ "
            elif (r,c) == START:       row += f" {arrows[pol_2d[r,c]]}S  "
            else:                      row += f"  {arrows[pol_2d[r,c]]}  "
        print(row)
    print("\nValue Function (full battery):")
    print("    " + "  ".join(f"  C{c}  " for c in range(COLS)))
    for r in range(ROWS):
        row = f"R{r} "
        for c in range(COLS):
            row += f"{V_grid[r, c, MAX_BATTERY]:+6.1f} "
        print(row)

print("\n" + "=" * 50)
print("            RESULTS")
print("=" * 50)

# VI policy as 2D (at full battery)
print_grid("=== Value Iteration Policy ===", vi_policy, V)

# PI policy as 2D (at full battery)
pi_policy_2d = policy[:, :, MAX_BATTERY]
print_grid("=== Policy Iteration Policy ===", pi_policy_2d, V2)

"""exp **4**"""

import numpy as np
import matplotlib.pyplot as plt

# ─────────────────────────────────────────
# SETUP — User Input (press Enter to use defaults)
# ─────────────────────────────────────────

def ask(prompt, default):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else str(default)

print("=" * 55)
print("   FINANCIAL TRADING MDP — SETUP")
print("   (Press Enter to use default values)")
print("=" * 55)

NUM_STATES  = int(ask("\nNumber of states",  3))
NUM_ACTIONS = int(ask("Number of actions", 3))

print("\nAction names:")
DEFAULT_ACTIONS = ["Sell", "Hold", "Buy"]
ACTION_NAMES = []
for a in range(NUM_ACTIONS):
    d = DEFAULT_ACTIONS[a] if a < len(DEFAULT_ACTIONS) else f"Action{a}"
    ACTION_NAMES.append(ask(f"  Action {a} name", d))

print("\nState names:")
DEFAULT_STATES = ["Bear", "Neutral", "Bull"]
STATE_NAMES = []
for s in range(NUM_STATES):
    d = DEFAULT_STATES[s] if s < len(DEFAULT_STATES) else f"State{s}"
    STATE_NAMES.append(ask(f"  State {s} name", d))

# ── Default transition probabilities ──
# Rows = current state, Cols = next state
DEFAULT_P = {
    # From Bear:   Sell→stay bear,  Hold→mix,     Buy→more bullish
    (0, 0): [0.7, 0.2, 0.1],
    (0, 1): [0.4, 0.4, 0.2],
    (0, 2): [0.3, 0.3, 0.4],
    # From Neutral: Sell→bearish,  Hold→stay,    Buy→bullish
    (1, 0): [0.3, 0.4, 0.3],
    (1, 1): [0.2, 0.5, 0.3],
    (1, 2): [0.1, 0.3, 0.6],
    # From Bull:   Sell→safe,      Hold→stays,   Buy→stays bull
    (2, 0): [0.2, 0.3, 0.5],
    (2, 1): [0.1, 0.3, 0.6],
    (2, 2): [0.1, 0.2, 0.7],
}

# ── Default rewards ──
DEFAULT_R = {
    (0, 0): +3,   # Bear  + Sell  = safe exit
    (0, 1): -1,   # Bear  + Hold  = small loss
    (0, 2): -4,   # Bear  + Buy   = risky
    (1, 0): +1,   # Neutral + Sell
    (1, 1): +2,   # Neutral + Hold
    (1, 2): +3,   # Neutral + Buy
    (2, 0): +2,   # Bull + Sell   = lock in profit
    (2, 1): +4,   # Bull + Hold
    (2, 2): +6,   # Bull + Buy    = max profit
}

print("\nEnter TRANSITION PROBABILITIES (or press Enter for defaults):")
P = np.zeros((NUM_STATES, NUM_ACTIONS, NUM_STATES))
for s in range(NUM_STATES):
    for a in range(NUM_ACTIONS):
        d = DEFAULT_P.get((s, a), [1/NUM_STATES]*NUM_STATES)
        d_str = " ".join(map(str, d))
        while True:
            raw = ask(f"  '{STATE_NAMES[s]}' via '{ACTION_NAMES[a]}' → probs", d_str)
            probs = list(map(float, raw.split()))
            if len(probs) == NUM_STATES and abs(sum(probs) - 1.0) < 1e-6:
                P[s][a] = probs
                break
            print(f"  ✗ Need exactly {NUM_STATES} values summing to 1.0")

print("\nEnter REWARDS (or press Enter for defaults):")
R = np.zeros((NUM_STATES, NUM_ACTIONS))
for s in range(NUM_STATES):
    for a in range(NUM_ACTIONS):
        d = DEFAULT_R.get((s, a), 0)
        R[s][a] = float(ask(f"  Reward: '{STATE_NAMES[s]}' via '{ACTION_NAMES[a]}'", d))

GAMMA = float(ask("\nDiscount factor gamma", 0.9))

print("\nINITIAL POLICY — action index per state:")
print("Actions:", {i: n for i, n in enumerate(ACTION_NAMES)})
DEFAULT_INIT = [0, 1, 2]   # Sell in Bear, Hold in Neutral, Buy in Bull
policy = np.array([
    int(ask(f"  Initial action for '{STATE_NAMES[s]}'",
            DEFAULT_INIT[s] if s < len(DEFAULT_INIT) else 0))
    for s in range(NUM_STATES)
])

# ─────────────────────────────────────────
# POLICY EVALUATION
# ─────────────────────────────────────────

def policy_evaluation(policy, P, R, gamma):
    V = np.zeros(NUM_STATES)
    while True:
        delta = 0
        for s in range(NUM_STATES):
            a = policy[s]
            v = sum(P[s][a][s2] * (R[s][a] + gamma * V[s2]) for s2 in range(NUM_STATES))
            delta = max(delta, abs(v - V[s]))
            V[s] = v
        if delta < 1e-6:
            break
    return V

# ─────────────────────────────────────────
# POLICY IMPROVEMENT
# ─────────────────────────────────────────

def policy_improvement(V, P, R, gamma):
    new_policy = np.zeros(NUM_STATES, dtype=int)
    for s in range(NUM_STATES):
        q = [sum(P[s][a][s2] * (R[s][a] + gamma * V[s2]) for s2 in range(NUM_STATES))
             for a in range(NUM_ACTIONS)]
        new_policy[s] = np.argmax(q)
    return new_policy

# ─────────────────────────────────────────
# POLICY ITERATION LOOP
# ─────────────────────────────────────────

print("\nRunning...\n")
history = []
pi_iter = 0

while True:
    V = policy_evaluation(policy, P, R, GAMMA)
    history.append((pi_iter, policy.copy(), V.copy()))
    new_policy = policy_improvement(V, P, R, GAMMA)
    pi_iter += 1
    if np.array_equal(new_policy, policy):
        print(f"Converged in {pi_iter} iteration(s).")
        break
    policy = new_policy

# ─────────────────────────────────────────
# RESULTS
# ─────────────────────────────────────────

print("\n" + "=" * 45)
print("            RESULTS")
print("=" * 45)

print("\nOptimal Policy:")
for s in range(NUM_STATES):
    print(f"  {STATE_NAMES[s]:10s} → {ACTION_NAMES[policy[s]]}")

print("\nOptimal Value Function:")
for s in range(NUM_STATES):
    print(f"  V({STATE_NAMES[s]:10s}) = {V[s]:.4f}")

print("\nPolicy Evolution:")
for i, pol, v in history:
    print(f"  Iter {i}: {[ACTION_NAMES[pol[s]] for s in range(NUM_STATES)]}")

# ─────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle("Financial Trading MDP — Policy Evaluation & Improvement", fontweight='bold')

for i, pol, v in history:
    axes[0].plot(STATE_NAMES, v, marker='o', label=f"Iter {i}")
axes[0].set_title("Value Function across Iterations")
axes[0].set_xlabel("State")
axes[0].set_ylabel("V(s)")
axes[0].legend()
axes[0].grid(alpha=0.3)

colors = ['tomato', 'steelblue', 'seagreen', 'goldenrod', 'mediumpurple']
axes[1].bar(STATE_NAMES, V, color=colors[:NUM_STATES])
for i, v in enumerate(V):
    axes[1].text(i, v + 0.1, f"{v:.2f}", ha='center', fontsize=10)
axes[1].set_title("Optimal Value Function")
axes[1].set_xlabel("State")
axes[1].set_ylabel("V(s)")
axes[1].grid(alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig("financial_mdp.png", dpi=150)
plt.show()
print("Plot saved as financial_mdp.png")

"""exp **5**"""

import numpy as np
from collections import defaultdict

# ─────────────────────────────────────────
# SETUP
# ─────────────────────────────────────────

def ask(prompt, default):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else str(default)

EPISODES = int(ask("Number of episodes", 50000))
EPSILON  = float(ask("Epsilon", 0.1))
GAMMA    = float(ask("Gamma", 1.0))

# ─────────────────────────────────────────
# ENVIRONMENT
# ─────────────────────────────────────────

def draw_card():
    return min(np.random.randint(1, 14), 10)

def hand_value(hand):
    total = sum(hand)
    if 1 in hand and total + 10 <= 21:
        return total + 10, True
    return total, False

def play_episode(policy=None, epsilon=0.0):
    player = [draw_card(), draw_card()]
    dealer = [draw_card(), draw_card()]
    states_actions = []

    while True:
        p_sum, usable = hand_value(player)
        state = (p_sum, dealer[0], usable)
        if p_sum >= 21:
            break
        if policy is None or np.random.random() < epsilon:
            action = np.random.randint(2)
        else:
            action = policy.get(state, 1)
        states_actions.append((state, action))
        if action == 0:
            break
        player.append(draw_card())

    while hand_value(dealer)[0] < 17:
        dealer.append(draw_card())

    p_final, d_final = hand_value(player)[0], hand_value(dealer)[0]

    if   p_final > 21:               reward = -1
    elif d_final > 21 or p_final > d_final: reward = +1
    elif p_final == d_final:         reward =  0
    else:                            reward = -1

    return states_actions, reward

# ─────────────────────────────────────────
# PART 1 — MC Prediction (estimate V(s))
# ─────────────────────────────────────────

V, V_count = defaultdict(float), defaultdict(int)

for _ in range(EPISODES):
    sa, reward = play_episode()
    visited = set()
    for state, action in sa:
        if state not in visited:
            visited.add(state)
            V_count[state] += 1
            V[state] += (reward - V[state]) / V_count[state]

# ─────────────────────────────────────────
# PART 2 — MC Control (find optimal policy)
# ─────────────────────────────────────────

Q       = defaultdict(lambda: np.zeros(2))
Q_count = defaultdict(lambda: np.zeros(2))
policy  = {}

for _ in range(EPISODES):
    sa, reward = play_episode(policy, EPSILON)
    visited = set()
    for state, action in sa:
        if (state, action) not in visited:
            visited.add((state, action))
            Q_count[state][action] += 1
            Q[state][action] += (reward - Q[state][action]) / Q_count[state][action]
        policy[state] = int(np.argmax(Q[state]))

# ─────────────────────────────────────────
# RESULTS
# ─────────────────────────────────────────

print("\n=== MC Prediction — V(s) (no usable ace) ===")
print(f"{'Player':>8}  {'Dealer':>8}  {'V(s)':>8}")
for p in range(12, 22):
    for d in [2, 6, 10]:
        s = (p, d, False)
        if s in V:
            print(f"{p:>8}  {d:>8}  {V[s]:>+.3f}")

print("\n=== MC Control — Optimal Policy (no usable ace) ===")
print(f"{'Player':>8}  {'Dealer':>8}  {'Action':>8}")
for p in range(12, 22):
    for d in [2, 6, 10]:
        s = (p, d, False)
        if s in policy:
            print(f"{p:>8}  {d:>8}  {'Stick' if policy[s]==0 else 'Hit':>8}")

"""EXP 6"""

import numpy as np
import random

# ─────────────────────────────────────────
# SETUP
# ─────────────────────────────────────────

grid_size   = 4
start_state = (0, 0)
goal_state  = (3, 3)

actions = {
    0: (-1,  0),  # Up
    1: ( 1,  0),  # Down
    2: ( 0, -1),  # Left
    3: ( 0,  1)   # Right
}

# Hyperparameters
alpha   = 0.1   # Learning rate
gamma   = 0.9   # Discount factor
epsilon = 0.2   # Exploration rate
episodes = 500

# ─────────────────────────────────────────
# ENVIRONMENT
# ─────────────────────────────────────────

def step(state, action):
    move = actions[action]
    next_state = (state[0] + move[0], state[1] + move[1])

    # Stay in place if out of bounds
    if next_state[0] < 0 or next_state[0] >= grid_size or \
       next_state[1] < 0 or next_state[1] >= grid_size:
        next_state = state

    if next_state == goal_state:
        return next_state, +10, True
    else:
        return next_state, -1, False

# ─────────────────────────────────────────
# PART 1 — TD(0) Prediction
# ─────────────────────────────────────────

V = np.zeros((grid_size, grid_size))

for ep in range(episodes):
    state = start_state
    for _ in range(200):
        action = random.randint(0, 3)           # Random policy
        next_state, reward, done = step(state, action)

        # TD(0) update
        td_target = reward + gamma * V[next_state[0]][next_state[1]]
        td_error  = td_target - V[state[0]][state[1]]
        V[state[0]][state[1]] += alpha * td_error

        state = next_state
        if done:
            break

print("TD(0) State Value Table (V under random policy):")
print(np.round(V, 2))

# ─────────────────────────────────────────
# PART 2 — Q-Learning
# ─────────────────────────────────────────

q_table = np.zeros((grid_size, grid_size, 4))

def choose_action(state):
    if random.uniform(0, 1) < epsilon:
        return random.randint(0, 3)             # Explore
    else:
        return np.argmax(q_table[state[0], state[1]])  # Exploit

for ep in range(episodes):
    state = start_state
    for _ in range(200):
        action = choose_action(state)
        next_state, reward, done = step(state, action)

        # Q-Learning update (Bellman equation)
        best_next = np.max(q_table[next_state[0], next_state[1]])
        q_table[state[0], state[1], action] += alpha * (
            reward + gamma * best_next - q_table[state[0], state[1], action]
        )

        state = next_state
        if done:
            break

# Extract greedy policy
arrows = ["↑", "↓", "←", "→"]

print("\nQ-Learning — Optimal Q-Value per State:")
print(np.round(np.max(q_table, axis=2), 2))

print("\nQ-Learning — Optimal Policy:")
for r in range(grid_size):
    row = ""
    for c in range(grid_size):
        if (r, c) == goal_state:
            row += "  G "
        else:
            row += f"  {arrows[np.argmax(q_table[r, c])]}"
    print(row)

"""EXP **7**"""

import numpy as np
import matplotlib.pyplot as plt

# ─────────────────────────────────────────
# SETUP
# ─────────────────────────────────────────

def ask(prompt, default):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else str(default)

print("=" * 55)
print("  E-COMMERCE BANNER — BANDIT STRATEGY COMPARISON")
print("  (Press Enter to use defaults)")
print("=" * 55)

NUM_BANNERS = int(ask("\nNumber of banners (arms)", 5))
NUM_STEPS   = int(ask("Number of steps", 1000))

print("\nEnter TRUE click-through probability for each banner:")
TRUE_PROBS = []
defaults = [0.1, 0.3, 0.5, 0.4, 0.2]
for i in range(NUM_BANNERS):
    d = defaults[i] if i < len(defaults) else round(np.random.uniform(0.1, 0.6), 1)
    p = float(ask(f"  Banner {i+1} probability", d))
    TRUE_PROBS.append(p)

EPSILON     = float(ask("\nEpsilon for e-Greedy", 0.1))
INIT_VALUE  = float(ask("Optimistic initial value", 1.0))

# ─────────────────────────────────────────
# ENVIRONMENT
# ─────────────────────────────────────────

BEST_BANNER = np.argmax(TRUE_PROBS)

def pull(arm):
    return 1 if np.random.random() < TRUE_PROBS[arm] else 0

# ─────────────────────────────────────────
# STRATEGY 1 — Epsilon-Greedy
# ─────────────────────────────────────────

counts = np.zeros(NUM_BANNERS)
values = np.zeros(NUM_BANNERS)
eg_rewards, eg_optimal = [], []

for t in range(NUM_STEPS):
    arm = np.random.randint(NUM_BANNERS) if np.random.random() < EPSILON else np.argmax(values)
    r = pull(arm)
    counts[arm] += 1
    values[arm] += (r - values[arm]) / counts[arm]
    eg_rewards.append(r)
    eg_optimal.append(1 if arm == BEST_BANNER else 0)

# ─────────────────────────────────────────
# STRATEGY 2 — Optimistic Initialization
# ─────────────────────────────────────────

counts = np.zeros(NUM_BANNERS)
values = np.full(NUM_BANNERS, INIT_VALUE)   # Start with high optimistic values
oi_rewards, oi_optimal = [], []

for t in range(NUM_STEPS):
    arm = np.argmax(values)                 # Always greedy — optimism drives exploration
    r = pull(arm)
    counts[arm] += 1
    values[arm] += (r - values[arm]) / counts[arm]
    oi_rewards.append(r)
    oi_optimal.append(1 if arm == BEST_BANNER else 0)

# ─────────────────────────────────────────
# STRATEGY 3 — UCB
# ─────────────────────────────────────────

counts = np.zeros(NUM_BANNERS)
values = np.zeros(NUM_BANNERS)
ucb_rewards, ucb_optimal = [], []

for t in range(1, NUM_STEPS + 1):
    arm = t - 1 if t <= NUM_BANNERS else np.argmax(values + np.sqrt(2 * np.log(t) / (counts + 1e-9)))
    r = pull(arm)
    counts[arm] += 1
    values[arm] += (r - values[arm]) / counts[arm]
    ucb_rewards.append(r)
    ucb_optimal.append(1 if arm == BEST_BANNER else 0)

# ─────────────────────────────────────────
# RESULTS — Terminal
# ─────────────────────────────────────────

steps = np.arange(1, NUM_STEPS + 1)

eg_avg  = np.cumsum(eg_rewards)  / steps
oi_avg  = np.cumsum(oi_rewards)  / steps
ucb_avg = np.cumsum(ucb_rewards) / steps

eg_opt_rate  = np.cumsum(eg_optimal)  / steps * 100
oi_opt_rate  = np.cumsum(oi_optimal)  / steps * 100
ucb_opt_rate = np.cumsum(ucb_optimal) / steps * 100

print("\n" + "=" * 55)
print("                  RESULTS")
print("=" * 55)
print(f"\nBest Banner : Banner {BEST_BANNER+1}  (CTR = {TRUE_PROBS[BEST_BANNER]:.2f})")
print(f"Total Steps : {NUM_STEPS}\n")
print(f"{'Strategy':<28} {'Avg Reward':>12} {'Optimal %':>10}")
print("-" * 52)
print(f"{'e-Greedy (e='+str(EPSILON)+')':<28} {np.mean(eg_rewards):>12.4f} {np.mean(eg_optimal)*100:>9.1f}%")
print(f"{'Optimistic Init (v0='+str(INIT_VALUE)+')':<28} {np.mean(oi_rewards):>12.4f} {np.mean(oi_optimal)*100:>9.1f}%")
print(f"{'UCB':<28} {np.mean(ucb_rewards):>12.4f} {np.mean(ucb_optimal)*100:>9.1f}%")

# Regret = (best possible reward) - (actual reward)
best_reward = TRUE_PROBS[BEST_BANNER]
eg_regret  = np.cumsum(best_reward - np.array(eg_rewards))
oi_regret  = np.cumsum(best_reward - np.array(oi_rewards))
ucb_regret = np.cumsum(best_reward - np.array(ucb_rewards))

# ─────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("E-Commerce Banner — Bandit Strategy Comparison", fontsize=13, fontweight='bold')

# Plot 1: Average Reward
axes[0].plot(steps, eg_avg,  label=f"e-Greedy (e={EPSILON})", color="steelblue")
axes[0].plot(steps, oi_avg,  label=f"Optimistic (v0={INIT_VALUE})", color="darkorange")
axes[0].plot(steps, ucb_avg, label="UCB", color="green")
axes[0].axhline(best_reward, linestyle="--", color="red", alpha=0.5, label=f"Best CTR ({best_reward:.2f})")
axes[0].set_title("Average Reward over Time")
axes[0].set_xlabel("Steps")
axes[0].set_ylabel("Avg Reward")
axes[0].legend(fontsize=8)
axes[0].grid(alpha=0.3)

# Plot 2: Optimal Banner Selection Rate
axes[1].plot(steps, eg_opt_rate,  label=f"e-Greedy",   color="steelblue")
axes[1].plot(steps, oi_opt_rate,  label="Optimistic",  color="darkorange")
axes[1].plot(steps, ucb_opt_rate, label="UCB",         color="green")
axes[1].set_title("Optimal Banner Selection %")
axes[1].set_xlabel("Steps")
axes[1].set_ylabel("% Optimal Choices")
axes[1].legend(fontsize=8)
axes[1].grid(alpha=0.3)

# Plot 3: Cumulative Regret
axes[2].plot(steps, eg_regret,  label=f"e-Greedy",  color="steelblue")
axes[2].plot(steps, oi_regret,  label="Optimistic", color="darkorange")
axes[2].plot(steps, ucb_regret, label="UCB",        color="green")
axes[2].set_title("Cumulative Regret")
axes[2].set_xlabel("Steps")
axes[2].set_ylabel("Regret")
axes[2].legend(fontsize=8)
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("bandit_comparison.png", dpi=150)
plt.show()
print("\nPlot saved as bandit_comparison.png")

"""EXP 8 **bold text**"""

import numpy as np
import matplotlib.pyplot as plt

# ─────────────────────────────────────────
# SETUP
# ─────────────────────────────────────────

def ask(prompt, default):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else str(default)

print("=" * 55)
print("  ENERGY DEMAND — FUNCTION APPROXIMATION")
print("  (Press Enter to use defaults)")
print("=" * 55)

NUM_SAMPLES = int(ask("\nNumber of data samples", 200))
EPOCHS      = int(ask("Training epochs", 500))

# ─────────────────────────────────────────
# GENERATE SYNTHETIC ENERGY DATA
# ─────────────────────────────────────────

np.random.seed(42)
hours    = np.random.randint(0, 24, NUM_SAMPLES).astype(float)
temps    = np.random.uniform(15, 40, NUM_SAMPLES)
day_type = np.random.randint(0, 2, NUM_SAMPLES).astype(float)

demand = (
    50
    + 20 * np.sin(2 * np.pi * hours / 24)
    + 1.5 * temps
    - 10 * day_type
    + np.random.normal(0, 5, NUM_SAMPLES)
)

# Normalize features AND target
X = np.column_stack([hours, temps, day_type])
X = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-8)
X = np.hstack([np.ones((NUM_SAMPLES, 1)), X])   # bias column

# Normalize target to [0,1] range — prevents overflow
y_mean, y_std = demand.mean(), demand.std()
y = ((demand - y_mean) / y_std).reshape(-1, 1)

# Train/test split (80/20)
split = int(0.8 * NUM_SAMPLES)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# ─────────────────────────────────────────
# METHOD 1 — Linear Regression
# ─────────────────────────────────────────

def run_linear(X_train, y_train, X_test, y_test, epochs):
    lr = 0.01
    W  = np.zeros((X_train.shape[1], 1))
    losses = []
    for _ in range(epochs):
        pred  = X_train @ W
        error = pred - y_train
        W    -= lr * (X_train.T @ error) / len(y_train)
        losses.append(float(np.mean(error**2)))
    pred_test = X_test @ W
    # Denormalize
    pred_out = pred_test * y_std + y_mean
    true_out = y_test    * y_std + y_mean
    mse = float(np.mean((pred_out - true_out)**2))
    mae = float(np.mean(np.abs(pred_out - true_out)))
    return pred_out, losses, mse, mae

# ─────────────────────────────────────────
# METHOD 2 — Shallow Neural Network
# ─────────────────────────────────────────

def relu(x):   return np.maximum(0, x)
def relu_d(x): return (x > 0).astype(float)

def clip(g, threshold=1.0):
    """Gradient clipping — prevents exploding gradients."""
    norm = np.linalg.norm(g)
    return g * (threshold / norm) if norm > threshold else g

def run_neural(X_train, y_train, X_test, y_test, epochs, hidden=16):
    lr   = 0.001          # smaller LR for neural net
    n_in = X_train.shape[1]

    # Xavier initialization
    W1 = np.random.randn(n_in, hidden) * np.sqrt(2.0 / n_in)
    b1 = np.zeros((1, hidden))
    W2 = np.random.randn(hidden, 1)   * np.sqrt(2.0 / hidden)
    b2 = np.zeros((1, 1))

    losses = []
    for _ in range(epochs):
        # Forward
        z1   = X_train @ W1 + b1
        a1   = relu(z1)
        pred = a1 @ W2 + b2

        error = pred - y_train
        losses.append(float(np.mean(error**2)))

        # Backward with gradient clipping
        d_out = 2 * error / len(y_train)
        dW2   = clip(a1.T @ d_out)
        db2   = d_out.sum(axis=0, keepdims=True)
        d_h   = (d_out @ W2.T) * relu_d(z1)
        dW1   = clip(X_train.T @ d_h)
        db1   = d_h.sum(axis=0, keepdims=True)

        W2 -= lr * dW2;  b2 -= lr * db2
        W1 -= lr * dW1;  b1 -= lr * db1

    # Test
    a1_test   = relu(X_test @ W1 + b1)
    pred_test = a1_test @ W2 + b2

    # Denormalize
    pred_out = pred_test * y_std + y_mean
    true_out = y_test    * y_std + y_mean
    mse = float(np.mean((pred_out - true_out)**2))
    mae = float(np.mean(np.abs(pred_out - true_out)))
    return pred_out, losses, mse, mae

# ─────────────────────────────────────────
# RUN BOTH
# ─────────────────────────────────────────

print("\nTraining Linear Regression...")
lin_pred, lin_losses, lin_mse, lin_mae = run_linear(X_train, y_train, X_test, y_test, EPOCHS)

print("Training Neural Network...")
nn_pred,  nn_losses,  nn_mse,  nn_mae  = run_neural(X_train, y_train, X_test, y_test, EPOCHS)

# ─────────────────────────────────────────
# RESULTS — Terminal
# ─────────────────────────────────────────

true_out = y_test * y_std + y_mean

print("\n" + "=" * 45)
print("              RESULTS")
print("=" * 45)
print(f"\n{'Method':<25} {'MSE':>10} {'MAE':>10}")
print("-" * 45)
print(f"{'Linear Regression':<25} {lin_mse:>10.2f} {lin_mae:>10.2f}")
print(f"{'Neural Network':<25} {nn_mse:>10.2f} {nn_mae:>10.2f}")

print("\nSample Predictions:")
print(f"  {'Actual':>10}  {'Linear':>10}  {'Neural':>10}")
for i in range(min(8, len(true_out))):
    a = float(true_out[i])
    l = float(lin_pred[i])
    n = float(nn_pred[i])
    print(f"  {a:>10.2f}  {l:>10.2f}  {n:>10.2f}")

# ─────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle("Energy Demand — Function Approximation", fontsize=13, fontweight='bold')

# Plot 1: Training loss
axes[0].plot(lin_losses, label="Linear Regression", color="steelblue")
axes[0].plot(nn_losses,  label="Neural Network",    color="darkorange")
axes[0].set_title("Training Loss (MSE)")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("MSE")
axes[0].legend()
axes[0].grid(alpha=0.3)

mn, mx = float(true_out.min()), float(true_out.max())

# Plot 2: Actual vs Predicted — Linear
axes[1].scatter(true_out, lin_pred, alpha=0.6, color="steelblue", s=20)
axes[1].plot([mn, mx], [mn, mx], 'r--', label="Perfect fit")
axes[1].set_title(f"Linear Regression\nMSE={lin_mse:.2f}  MAE={lin_mae:.2f}")
axes[1].set_xlabel("Actual Demand")
axes[1].set_ylabel("Predicted Demand")
axes[1].legend(); axes[1].grid(alpha=0.3)

# Plot 3: Actual vs Predicted — Neural
axes[2].scatter(true_out, nn_pred, alpha=0.6, color="darkorange", s=20)
axes[2].plot([mn, mx], [mn, mx], 'r--', label="Perfect fit")
axes[2].set_title(f"Neural Network\nMSE={nn_mse:.2f}  MAE={nn_mae:.2f}")
axes[2].set_xlabel("Actual Demand")
axes[2].set_ylabel("Predicted Demand")
axes[2].legend(); axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("function_approximation.png", dpi=150)
plt.show()
print("\nPlot saved as function_approximation.png")